#PBS -l select=1:ncpus=32:mpiprocs=32:mem=124gb
#PBS -l walltime=10:00:00
#PBS -N SVM

# Load modules for any applications


module load anaconda3/personal
module load mpi

# Change to the directory the job was submitted from

cd $PBS_O_WORKDIR

# Run program, using 'mpiexec' to start the job
# mpiexec automatically picks up the # of cores
# assigned to the job. No other flags are required
#  - note: don't use 'mpirun'


mpiexec python3 SVM.py
