#PBS -l select=1:ncpus=32:mem=62gb
#PBS -l walltime=72:0:0
#PBS -N lightgbm_5yr

# Load modules for any applications


module load anaconda3/personal

# Change to the directory the job was submitted from

cd $PBS_O_WORKDIR

# Run program, using 'mpiexec' to start the job
# mpiexec automatically picks up the # of cores
# assigned to the job. No other flags are required
#  - note: don't use 'mpirun'


python3 Light_gbm.py
